version: "3.8"

services:
  dw_tool_db:
    container_name: dw_tool_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dw_tool
      POSTGRES_PASSWORD: dw_tool
    image: postgres:15.2-alpine3.17
